export {default as Home} from '../component/Home';
export {default as Login} from '../component/Login';
export {default as FinalCart} from '../component/FinalCart';
export {default as Menu} from '../pages/Menu';
export {default as Payment} from '../Payment/index';
export {default as PaymentSuccess} from '../Payment/PaySuccess';
export {default as PaymentResult} from '../PaymentResult/index';
export {default as MenuManage} from '../AdminPages/MenuManage';
export {default as Shop} from '../Shop/Shop';